api/urls.py
from django.urls import path

from home import views

app_name = "api"

urlpatterns = [
    
]

core/urls.py
from django.urls import path

from home import views

app_name = "core"

urlpatterns = [
    
]

home/urls.py
from django.urls import path

from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('create/category/', views.CreateCategory.as_view(), name="create_category"),
    path('detail/category/<int:pk>/', views.DetailCategory.as_view(), name="detail_category"),
    path('update/category/<int:pk>/', views.UpdateCategory.as_view(), name="update_category"),
    path('delete/category/<int:pk>/', views.DeleteCategory.as_view(), name="delete_category"),
    ### USERS URLS
    path('list/users/', views.UserList.as_view(), name="list_users"),
]

sysplaest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

api/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=16, default="Jhon Wick", blank=False, null=False)
    bio = models.TextField(max_length=256, default="I love This App..", blank=True, null=True)
    age = models.IntegerField(default=1)
    weight = models.FloatField(default=1.0)
    timestamp = models.DateField(auto_now_add=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=16)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=16)
    status = models.BooleanField(default=True)

    

home/forms.py
from django import forms

from .models import Category


class UpdateCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            "user",
            "name",
            "status"
        ]


class CreateCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            "user",
            "name",
            "status"
        ]

api/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from django.contrib.auth.models import User

from .models import Category
from .forms import UpdateCategoryForm, CreateCategoryForm
# Create your views here.


##### C R U D  CATEGORY #####

#CREATE
class CreateCategory(generic.CreateView):
    template_name = "home/create_category.html"
    model = Category
    form_class = CreateCategoryForm
    success_url = reverse_lazy("home:index")


#RETRIEVE
## List Categories
class Index(generic.View):
    template_name = "home/index.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "categories": Category.objects.all()
        }
        return render(request, self.template_name, self.context)
    

## Detail Category
class DetailCategory(generic.View):
    template_name = "home/detail_category.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "category": Category.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)



# UPDATE 
class UpdateCategory(generic.UpdateView):
    template_name = "home/update_category.html"
    model = Category
    form_class = UpdateCategoryForm
    success_url = reverse_lazy("home:index")


# DELETE 
class DeleteCategory(generic.DeleteView):
    template_name = "home/delete_category.html"
    model = Category
    success_url = reverse_lazy("home:index")


##### U S E R S  C R U D  #####

## RETRIEVE
# User List 
class UserList(generic.View):
    template_name = "home/list_users.html"
    context = {}

    def get(self, request):
        self.context = {
            "users": User.objects.all()
        }
        return render(request, self.template_name, self.context)

templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
        <!-- NAVBAR -->
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Navbar</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:list_users' %}">User's</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Category's Actions
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'home:create_category' %}">Create Category</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                  </li>
                </ul>
                <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
          <!-- END NAVBAR -->
        {% block content %}
        {% endblock content %}
    </div>
    
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.js' %}" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
  </body>
</html>

templates/home/about.html
{% extends 'base/base.html' %}

{% block title %} About View {% endblock title %}

{% block content %}

<h1>Hola {{ name }} Mucho Gusto en Conocerte!!</h1>
<br>
<a href="{% url 'home:index' %}" class="btn btn-outline-info">Go to Home</a>
{% endblock content %}

templates/home/create_category.html
{% extends 'base/base.html' %}

{% block title %}Create Category View{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <a href="{% url 'home:index' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-success">Create</button>
    </form>
{% endblock content %}

templates/home/delete_category.html
{% extends 'base/base.html' %}

{% block title %}Delete Category View{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <h3>Realmente deseas borra la categoria: {{ object }} ?</h3>
        <a href="{% url 'home:index' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-danger">Delete</button>
    </form>
{% endblock content %}

templates/home/detail_category.html
{% extends 'base/base.html' %}

{% block title %} Detail Category View {% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Category Name: <strong>{{ category.name }}</strong>
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the Id category:  {{ category.id }}</strong> It is shown by {{ category.user }}, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go view the status category:  <code>{{ category.status}}</code>, though the transition does limit overflow.
        
            <a href="{% url 'home:index' %}" class="btn btn-link">back</a>
        </div>
      </div>
    </div>
  </div>
    
    
{% endblock content %}

templates/home/index.html
{% extends 'base/base.html' %}

{% block title %} Index View {% endblock title %}

{% block content %}
    <div class="container-md">
        <table class="table table-striped">
            <thead>
                <th>ID</th>
                <th>NAME</th>
                <th>STATUS</th>
                <th></th>
                <th>ACTIONS</th>
                <th></th>
            </thead>
            <tbody>
                {% for category in categories %}
                    <tr>
                        <td>{{ category.id }}</td>
                        <td>{{ category.name }}</td>
                        <td>{{ category.status}}</td>
                        <td><a href="{% url 'home:detail_category' category.id %}" class="btn btn-outline-info">Detail</a></td>
                        <td><a href="{% url 'home:update_category' category.id %}" class="btn btn-outline-warning">Update</a></td>
                        <td><a href="{% url 'home:delete_category' category.id %}" class="btn btn-outline-danger">Delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

templates/home/list_users.html
{% extends 'base/base.html' %}
{% block title %}List Users View{% endblock title %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>USERNAME</th>
            <th>EMAIL</th>
            <th>STAFF</th>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.is_staff }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/home/update_category.html
{% extends 'base/base.html' %}

{% block title %}Update Category View{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <a href="{% url 'home:index' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-success">Update</button>
    </form>
{% endblock content %}